apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
  labels:
    app: jenkins-master
spec:
  selector:
    app: jenkins-master
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
